- Brocfile.js
QUnit file does not get transpiled anymore. This change slightly reduces build time (~0.5s) but leaves QUnit file non-minified (which is good for tests in my opinion). But the most important fact is that it allows to use strict mode in tests files (fixes #37). For now 1 test should expectedly fail (4 MockSocket inherits EventTarget: adding/removing "message" event listeners works) due to bug in the code and should be fixed by #38.
> Enable strict mode in tests

- src/server.js
- src/websocket.js
- test/functional-websockets-test.js
This PR adds the ability to simulate client authentication for native WebSockets.
- Server now takes an `options` Object as a second parameter. ([src](https://github.com/thoov/mock-socket/compare/master...ccummings:add-client-verification?expand=1#diff-e6a5b42b2f7a26c840607370aed5301aR23))
- If the `verifyClient` option is provided, it will be invoked on each client's connection attempt. If it returns falsy; the connection is closed and onerror is triggered. ([src](https://github.com/thoov/mock-socket/compare/master...ccummings:add-client-verification?expand=1#diff-7cd41e7e5548228ba13f537ea2a76a20R97))
`verifyClient` should return a boolean
- If the `verifyClient` option is missing, Server and WebSocket behave like before
> Adding client verification to Server.

- .eslintrc
- package.json
- src/server.js
- src/socket-io.js
- test/functional-socket-io-test.js
- test/unit-event-target-test.js
socket.emit('event-name', 'foo', 'bar', 'baz') is now supported.
Fixes: #81
> Allow emit to sent multiple arguments

- src/websocket.js
- test/functional-websockets-test.js
This bug was introduced by my previous PR (#82 ) where I added client auth.
If the `verifyClient` check fails, the websocket closes but does not remove the websocket from the network bridge.
> removing websocket from network bridge if verifyClient fails

- src/server.js
If after calling `Server.close()`, a websocket client's `onclose` handler immediately attempts to reconnect, then the connection will succeed because the server had not been removed before the notifications were sent.
I wonder if it might not be better, in general, to use `setTimeout(fn, 0)` to send notifications on the next event loop to prevent timing issues like this between the server and client.
> Fix bug in 'Server.close()' where clients were notified before server was removed

- src/server.js
- src/websocket.js
- tests/functional/websockets.test.js
this change adds the ability to support subprotocol selection for the `Server` class. This should resolve issue #181 
Example:
```
import { WebSocket, Server } from 'mock-server';
const server = new Server(url, {
selectProtocol(protocols) { return protocol[0]; }
});
const client = new WebSocket(url, ['foo', 'bar']);
```
> introduce support for server subprotocol selection

- src/websocket.js
- tests/issues/143.test.js
Hello !
This PR is to fix https://github.com/thoov/mock-socket/issues/143
Currently, the behaviour of mockSocket does not match websocket behaviour : reassigning a listener does not cancel previous listeners.
I implemented the workaround proposed in the issue.
> Issue 143 :: Reassigning listeners on MockSocket

- src/socket-io.js
- tests/unit/socket-io.test.js
- Passing through `protocol` option to SocketIo instance.
Fixes https://github.com/thoov/mock-socket/issues/201
> Passing protocol through instantiation code

- src/helpers/normalize-send.js
- src/server.js
- src/websocket.js
- tests/unit/server.test.js
If the data is not an ArrayBuffer/Blog it should be serialized to
a string.
> [BUG #212] Send data should be serialized to String

- src/socket-io.js
I'm trying to integrate this into an existing project which utilizes chaining with on(). 
`socket.on(...).on(...)`
This change matches the expected api of socket.io, which returns the socket for chaining.
https://socket.io/docs/client-api/#socket-on-eventname-callback
> Return 'this' from the socket methods for chaining

- index.d.ts
This provides a fix to error below:
```.../node_modules/mock-socket/index.d.ts
(47,8): Parameter 'any' implicitly has an 'any' type.
```
> Fix types to fit noImplicitAny option.

- index.d.ts
Solve https://github.com/thoov/mock-socket/issues/235 by replacing USVString with normal string.
Note that the definitions of WebSocket in lib.dom.d.ts currently
bundled with Typescript itself use normal strings exclusively:
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts
> Fix Cannot find name 'USVString' in Typescript

- index.d.ts
Currently, if you try to pass 'error' as the event argument, Typescript marks it as an error since it isn't an Event object. This PR changes the argument type to string to match the correct usage.
> Fix type for Server.simulate argument

- index.d.ts
Hi, thanks a lot for this library!
It seems that the following code causes an error because the `WebSocket` type definition lacks the `on` method:
```typescript
mockServer.on('connection', (socket: WebSocket) => {
socket.on('message', (data: string) => {
^^ Property 'on' does not exist on type 'WebSocket'.
// noop
})
})
```
This PR adds the missing `on` method using mapped values [as the official Typescript definition does](https://github.com/Microsoft/TypeScript/blob/v3.3.3333/lib/lib.dom.d.ts#L16355) but the following should also do:
```typescript
on(type: string, callback: (data: string | Blob | ArrayBuffer | ArrayBufferView) => void): void;
```
After all is seems that the code allows any types between the server and the client :smile:
> [IMPR] Typescript WebSocket missing proxyFactory "on" wrapper

- src/network-bridge.js
- tests/unit/network-bridge.test.js
Not sure if this is the best way to do it, happy to see comments.
> Ignore query parameters when attaching a websocket

- rollup.config.js
as given lack of `"type": "module"` in `package.json`, and `.js` extension  Node tries to resolve `import "mock-socket/dist/mock-socket.es.js"` as CommonJS, and throws Syntax errors on `export`
> Export ES Module format with .mjs extension,

- src/server.js
Heya,
Found a bug where readyState is undefined after closing the connection.
> Fixed undefined readyState for WebSockets after closing connection in Server

- src/helpers/array-helpers.js
The current version triggers an NPE when one tries to unregister an event type (using `.off(...)`) that does not have any associated handlers.
> Fix null pointer exceptions

- src/socket-io.js
- tests/unit/socket-io.test.js
> Add the hasListeners method to client socket.

- src/network-bridge.js
Apparently, [the fix](https://github.com/thoov/mock-socket/pull/275) for https://github.com/thoov/mock-socket/issues/274 was not complete.
These changes have to do the job.
Worked for me at least
> trim query params for attachServer method lookup

- index.d.ts
- tests/unit/websocket.test.js
Typescript expects the url in the constructor of a websocket to be of type `string | URL` as seen here: https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L17136. Update types to reflect this.
> Update type of url parameter of websocket constructor

- src/event/event.js
I leave as an exercise to the developers to propose a regression test. I spotted this in the wild and assume it can’t be right, but have not investigated further. It is not a problem for our usage.
> Address misspelling of cancelBuble

- src/algorithms/close.js
- tests/functional/websockets.test.js
Fix https://github.com/thoov/mock-socket/issues/298
> fix onclose event when client closes the connection

- README.md
- index.d.ts
- src/algorithms/close.js
- src/helpers/proxy-factory.js
- src/server.js
- tests/functional/close-algorithm.test.js
- tests/functional/websockets.test.js
- tests/unit/factory.test.js
- tests/unit/network-bridge.test.js
- tests/unit/server.test.js
1. fix server-side socket listeners. Fixes https://github.com/thoov/mock-socket/pull/372
2. add off method to remove the listener. Fixes https://github.com/thoov/mock-socket/issues/371
> Handle proxy events properly

- src/server.js
- src/socket-io.js
Thanks for keeping this package maintained!
This PR is a follow-up from https://github.com/thoov/mock-socket/pull/246, where this issue has already been discussed 1.5 years ago. We lost track of that PR (by @thomasdunn) and want to submit it again in a proper form such that it can merged in master.
Note that this code has been running in our own fork for about 1.5 years without any issues.
> Do not normalize data when emitting to socket.io sockets

- src/websocket.js
- tests/unit/server.test.js
- tests/unit/websocket.test.js
> The `send()` method now only throws when the socket is in the `CONNECTING` state

- src/websocket.js
- tests/functional/close-algorithm.test.js
1. A test case that demonstrates the bug described in #384.
2. Code that bails out of the constructor's delayed setup in the event that the socket is no longer in the `CONNECTING` state.
Fixes #384.
> Calling `close` in the `CONNECTING` state should not cause `onopen` to be called
